#!/bin/sh
cd "${0%build}" || exit 1

build() {
	${X}gcc -c -O2 $C src/*.c -I. -I../zlib/src
	${X}gcc *.o -shared -o ../../bin/$P/$D -L../../bin/$P -lz $L
	rm -f      ../../bin/$P/$A
	${X}ar rcs ../../bin/$P/$A *.o
	rm *.o
}

if [ "$OSTYPE" = "msys" ]; then
	P=windows L="-s -static-libgcc" D=png.dll A=png.a build
elif [ "${OSTYPE#darwin}" != "$OSTYPE" ]; then
	P=osx64 C="-arch x86_64" L="-arch x86_64 -install_name @rpath/libpng.dylib" \
	D=libpng.dylib A=libpng.a build
else
	P=linux C="-fPIC -U_FORTIFY_SOURCE" L="-s -static-libgcc" \
	D=libpng.so A=libpng.a build
fi
